# Arrays and Matrices Hands-On

## Kai Bartlette

Please complete the following tasks in a Jupyter Notebook file, using the numpy package:

Create a five element array using your favorite numbers named myFavorites.

Perform each of the five aggregate functions on your array.

Create a five element array containing only ones named OneArrayToRuleThemAll.

Add myFavorites and OneArrayToRuleThemAll.

Multiply every element in myFavorites by two.

Call the third element in myFavorites using indexing.

Create a four element, two-by-two matrix of numbers named TheMatrixHasYou.

Access the upper left element in TheMatrixHasYou using indexing.

Find the largest number in each row for TheMatrixHasYou.

Reshape TheMatrixHasYou into a matrix with one row and four columns.


In [1]:
import numpy as np

In [6]:
myFavorites = np.array([42, 39, 101, 18, 75])

myFavorites.max()

101

In [7]:
myFavorites.min()

18

In [8]:
myFavorites.mean()

55.0

In [9]:
myFavorites.std()

29.359836511806396

In [10]:
myFavorites.sum()

275

In [13]:
OneArrayToRuleThemAll = np.ones(5)

In [14]:
myFavorites + OneArrayToRuleThemAll

array([ 43.,  40., 102.,  19.,  76.])

In [15]:
myFavorites * 2

array([ 84,  78, 202,  36, 150])

In [16]:
myFavorites[2]

101

In [20]:
TheMatrixHasYou = np.array([[1,2,3,4],[5,6,7,8]])

In [21]:
TheMatrixHasYou

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
TheMatrixHasYou[0,0]

1

In [23]:
TheMatrixHasYou.max(axis=1)

array([4, 8])

In [24]:
TheMatrixHasYou.reshape(1,4)

ValueError: cannot reshape array of size 8 into shape (1,4)

In [ ]:
TheMatrixHasYou cannot be reshaped into an array with only one row and four columns; it must be divisible by 8.